export const SKILL_TAXONOMY = [
  { name: 'Python', slug: 'python', category: 'language', aliases: ['py', 'python3'] },
  { name: 'JavaScript', slug: 'javascript', category: 'language', aliases: ['js', 'es6', 'es2015'] },
  { name: 'TypeScript', slug: 'typescript', category: 'language', aliases: ['ts'] },
  { name: 'Java', slug: 'java', category: 'language', aliases: ['java8', 'java11'] },
  { name: 'C++', slug: 'cpp', category: 'language', aliases: ['c plus plus', 'cplusplus'] },
  { name: 'Go', slug: 'go', category: 'language', aliases: ['golang'] },
  { name: 'React', slug: 'react', category: 'framework', aliases: ['reactjs', 'react.js'] },
  { name: 'Node.js', slug: 'nodejs', category: 'framework', aliases: ['node'] },
  { name: 'Django', slug: 'django', category: 'framework', aliases: [] },
  { name: 'FastAPI', slug: 'fastapi', category: 'framework', aliases: ['fast api'] },
  { name: 'Spring Boot', slug: 'spring-boot', category: 'framework', aliases: ['spring', 'springboot'] },
  { name: 'Express.js', slug: 'express', category: 'framework', aliases: ['express', 'expressjs'] },
  { name: 'PostgreSQL', slug: 'postgresql', category: 'database', aliases: ['postgres', 'pg'] },
  { name: 'MySQL', slug: 'mysql', category: 'database', aliases: [] },
  { name: 'MongoDB', slug: 'mongodb', category: 'database', aliases: ['mongo'] },
  { name: 'Redis', slug: 'redis', category: 'database', aliases: [] },
  { name: 'SQL', slug: 'sql', category: 'database', aliases: ['structured query language'] },
  { name: 'Docker', slug: 'docker', category: 'cloud', aliases: ['containerization'] },
  { name: 'Kubernetes', slug: 'kubernetes', category: 'cloud', aliases: ['k8s'] },
  { name: 'AWS', slug: 'aws', category: 'cloud', aliases: ['amazon web services', 'amazon aws'] },
  { name: 'CI/CD', slug: 'cicd', category: 'cloud', aliases: ['ci cd', 'continuous integration'] },
  { name: 'Git', slug: 'git', category: 'tool', aliases: ['github', 'gitlab', 'version control'] },
  { name: 'REST APIs', slug: 'rest-api', category: 'tool', aliases: ['rest', 'restful', 'api'] },
  { name: 'GraphQL', slug: 'graphql', category: 'tool', aliases: [] },
  { name: 'System Design', slug: 'system-design', category: 'tool', aliases: ['distributed systems', 'hld', 'lld'] },
  { name: 'DSA', slug: 'dsa', category: 'tool', aliases: ['data structures', 'algorithms', 'leetcode'] },
];
